name: gh-pages
# This workflow is triggered on pushes to the master branch.
on:
  push:
    branches:
      - master

jobs:
  build:
    name: push-gh-pages
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run predeploy
      - name: Publish gh-pages
        run: npm run deploy
