name: publish-on-gh-pages
# This workflow is triggered on pushes to the master branch.
on:
  push:
    branches:
      - master

jobs:
  build:
    # Job name is Greeting
    name: push-gh-pages
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: npm install
      - name: "Publish gh-pages"
        id: publish
        run: npm run publish
      # This step prints an output from the previous step's action.
      - name: "Print output"
        run: echo '${{ steps.publish }}.'
